/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bursaryManagement;

import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import projectConnectors.SelectFromDB;

/**
 *
 * @author pm271
 */
public class ApprovedList extends javax.swing.JFrame {

    /**
     * Creates new form ApprovedList
     */
    public ApprovedList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddApprove = new javax.swing.JButton();
        jButtonMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("SUCCESSFUL APPLICANT LIST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonBack.setBackground(new java.awt.Color(204, 0, 0));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 99, 44));

        jButtonPrint.setBackground(new java.awt.Color(0, 153, 0));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("PRINT THIS LIST");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search For Applicant");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jTextFieldSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 300, 37));

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 90, 37));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Adm Number", "Gender", "Institution Name", "Campus", "Year Of Study", "County Ward", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1310, 450));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1513, 162, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 815, -1, -1));

        jButtonAddApprove.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAddApprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddApprove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddApprove.setText("ADD APPROVED LIST");
        jButtonAddApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddApproveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 190, 50));

        jButtonMessage.setBackground(new java.awt.Color(0, 153, 0));
        jButtonMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMessage.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMessage.setText("SEND APPROVAL MESSAGE");
        jButtonMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMessageActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 230, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        setVisible(false);
        new AdminHomePage().setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs = SelectFromDB.getData("(SELECT * FROM biaBursaryForm WHERE scoreInPercent>=60)UNION(SELECT * FROM flaBursaryForm WHERE scoreInPercent>=60)UNION(SELECT * FROM menBursaryForm WHERE scoreInPercent>=60)UNION(SELECT * FROM nkrBursaryForm WHERE scoreInPercent>=60)");
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(10),rs.getString(18),rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String search = jTextFieldSearch.getText();
        if(search.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Student Name or School to find details!");
        }
        else{
            ResultSet rs = SelectFromDB.getData("(SELECT * FROM biaBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM flaBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM menBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM nkrBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)");
            DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            try {
                 while(rs.next()){
                     model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(10),rs.getString(18),rs.getString(5)});
                }
                rs.close();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
         String search = jTextFieldSearch.getText();
          ResultSet rs = SelectFromDB.getData("(SELECT * FROM biaBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM flaBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM menBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)UNION(SELECT * FROM nkrBursaryForm WHERE studentName LIKE '%"+search+"%' and scoreInPercent>=60 or institutionName LIKE '%"+search+"%' and scoreInPercent>=60)");
          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
            try {
                 while(rs.next()){
                     model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(10),rs.getString(18),rs.getString(5)});
                }
                rs.close();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        MessageFormat header = new MessageFormat("NAKURU TOWN EAST CONSTITUENCY");
        MessageFormat footer = new MessageFormat("CHEQUES HAVE BEEN DISBURSED, CONFIRMED WITH YOUR INSTITUTION FINANCE");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DOCUMENT CANNOT BE PRINTED AT THIS TIME"+e.getMessage());
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonAddApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddApproveActionPerformed
        ResultSet rs = SelectFromDB.getData("(SELECT * FROM biaBursaryForm WHERE scoreInPercent>=50)UNION(SELECT * FROM flaBursaryForm WHERE scoreInPercent>=50)UNION(SELECT * FROM menBursaryForm WHERE scoreInPercent>=50)UNION(SELECT * FROM nkrBursaryForm WHERE scoreInPercent>=50)");
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(10),rs.getString(18),rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonAddApproveActionPerformed

    private void jButtonMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMessageActionPerformed
        new SmsPage().setVisible(true);
    }//GEN-LAST:event_jButtonMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovedList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddApprove;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonMessage;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
